### ISSUE TITLE
Plots may not work with Debian's matplotlib package

### ISSUE THREAD

**Issue by nham** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#108]
I'm filing this to report an experience with getting the plots in the book to work on Debian Jessie using Python 3.

While using the `python3-matplotlib` package (which has matplotlib 1.4.2 currently), upon executing the notebook cells with plots (both the interactive and non-interactive plots), I would not get any errors, but none of the plots would show up. I managed to fix this by uninstalling the Debian package and installing matplotlib through pip (that is, the `pip3` command, since I'm using Python 3).

**Comment by rlabbe** [comment]
I haven't investigated this in detail, but for better and worse I stay pretty bleeding edge in my package requirements. 

For 'worse' this means the book may not work with Python distributed with some linux distributions.

For 'better' I can use the most recent changes to Jupyter - they are moving fast, breaking compatibility, and I'd rather be on the front of that. It is discouraging to have to provide 'technical support' to a book because the tools are changing. Staying current means greater likelihood of the book still working in the future.
