### ISSUE TITLE
Math Typo in UKF Notebook

### ISSUE THREAD

**Issue by ajRiverav** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#173]
In describing the use of the Cholesky decomposition, the Sigma Points section (just before [35]) has a math typo in A=LL* 

It seems to be a github viewer issue as the nbviewer shows the correct equation. 

[UKF notebook link](https://github.com/rlabbe/Kalman-and-Bayesian-Filters-in-Python/blob/master/10-Unscented-Kalman-Filter.ipynb)

**Comment by rlabbe** [comment]
I can't do anything about how github renders notebooks; it does many unpleasant things with LaTeX. For just one example, it ignores the \mathsf command, so every T for transpose is rendered with serifs, which is wrong, but fortunately just a typography issue.

Since I cannot fix how github renders LaTeX, I'm going to close this issue.
