### ISSUE TITLE
Issue with imports in fresh environment

### ISSUE THREAD

**Issue by atyshka** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#264]
I'm using this notebook on my mac and I've had it working just fine for a while. All of a sudden now when I try to "run all" I get this:

`SyntaxError: from __future__ imports must occur at the beginning of the file`

This happens in every page in the notebook.
I'm using a conda environment as described in the README. I thought that I might have messed something up, but I tried with a fresh clone and new conda environment. Any obvious mistakes I'm making or is this an error in the code?

**Comment by rummanwaqar** [comment]
I had the same problem. Its because future statement must appear near the top of the module. The only lines that can appear before a future statement are:
* the module docstring (if any),
* comments,
* blank lines, and
* other future statements.

There is `%matplotlib inline` line before it causing issues.

**Comment by rummanwaqar** [comment]
@rlabbe can I make a PR to fix this?

**Comment by rlabbe** [comment]
Sure
