### ISSUE TITLE
Incorrect indexing of transition probability matrix?

### ISSUE THREAD

**Issue by jwdink** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#271]
In the chapter on adaptive filtering, in the IMM section:

> In other words M[i, j] is the probability of mode being *i* given that the last mode was *j*. In this example the probability of the mode currently being straight (*i*=0) given that the last mode was a turn (*j*=1) is M[1,0] = 0.05. In Python we'd write:

    M = np.array([[.97, .03], [.05, .95]])
    array([[0.97, 0.03],
           [0.05, 0.95]])

The description seems to be misaligned with the indexing. In the description, rows capture "transition to" and columns capture "transition from". So the first row says we're transition *to* straight, and the second column says we're transitioning *from* turning.

However, M[1,0] is the reverse: it's the second row, first column. And overall, the M array seems to use rows to indicate "transition from" and columns to indicate "transition to". This aligns with the fact that the rows sum to one (but the columns do not).

Which of these descriptions is correct? I think this issue might propagate into the actual [IMM code](https://github.com/rlabbe/filterpy/blob/master/filterpy/kalman/IMM.py), but I'm not sure.

**Comment by techniccontroller** [comment]
Yes exactly. I also noticed this mistake. 

The IMM code is implemented such that the probability of transitioning from state j to state i is in row j and column i. 
However, in the documentation of the [IMMEstimator](https://github.com/rlabbe/filterpy/blob/master/filterpy/kalman/IMM.py) and here in the chapter on adaptive filtering the designation M[ i, j ] is wrong. It have to be M[ j, i ] (where the first index is the row and the second is the column).

IMM.py (from filterpy):
>  M : (N, N) ndarray of float
        Markov chain transition matrix. ~~M[i,j]~~ **M[ j, i ]** is the probability of
        switching from filter j to filter i.

14-Adaptive-Filtering.ipynb:
> In other words ~~M[i,j]~~ **M[ j, i ]**  is the probability of mode being i given that the last mode was j. In this example the probability of the mode currently being straight (i=0) given that the last mode was a turn (j=1) is M[1,0] = 0.05. In Python we'd write:

The code is working correctly and was very helpful for my university project, but of course the description should be correct, too. 
I hope it will be fixed in future.

Regards 
Edgar

**Comment by rlabbe** [comment]
Thanks guys, fixed.
