### ISSUE TITLE
Chapter 2+ is not rendering on NBViewer

### ISSUE THREAD

**Issue by k-sys** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#333]
https://nbviewer.jupyter.org/github/rlabbe/Kalman-and-Bayesian-Filters-in-Python/blob/master/02-Discrete-Bayes.ipynb

**Comment by rlabbe** [comment]
I just did a merge that might fix this; it takes nbviewer awhile to update it's cache so I can't yet validate that it worked.

**Comment by The-Fenix** [comment]
Take me off of this chain please

Jason Wilson
Certified Pressure Testing LLC, Delaware- DBA Certified Holdings LLC
2019 State Route 821
Building 25
Marietta OH 45750
Cell 517-256-6561
jwilson@<mailto:|jwilson@certifiedholdingsllc.com|>cptllc.net
          www.certifiedpressuretesting.com<http://www.certifiedpressuretesting.com/>


On May 3, 2020, at 1:53 PM, Roger Labbe <notifications@github.com> wrote:

﻿

I just did a merge that might fix this; it takes nbviewer awhile to update it's cache so I can't yet validate that it worked.

**Comment by rlabbe** [comment]
Jason,
I cannot, this is managed by the third party software at  github.com The github user isnyder@certifiedtechnologies.com subscribed to this. you have an email signature of jwilson@certifiedtechnologies.com. I'm guessing maybe your IT has linked your email to isynyder somehow?

In any case, there is an unsubscribe link at the bottom of the emails you are receiving. If that doesn't work see if your IT department can break the link. Or, if isnyder is also you, or still works at the company, have them "unstart" the repository https://github.com/rlabbe/Kalman-and-Bayesian-Filters-in-Python

Continued requests to remove you will have no effect. I cannot remove you; you have to remove you. As a last resort go to github help and contact them and ask them to fix this: https://help.github.com/en

**Comment by rlabbe** [comment]
Merge still isn't rendering correctly, but if you put the commit SHA in the address instead of `master` it renders fine: https://nbviewer.jupyter.org/github/rlabbe/Kalman-and-Bayesian-Filters-in-Python/blob/4308372241fc870f21187ddf611b1133656e5525/02-Discrete-Bayes.ipynb

I don't know if this is a caching issue, a bug in nbviewer, or what. I've asked on gitter; in the meantime try using the SHA (easily accessible by viewing page in github, clicking on the icon on the upper right top of the page and clicking the link for nbviewer).

**Comment by rlabbe** [comment]
Okay, it seems to be rendering fine now. Reopen if you are still having problems.
