### ISSUE TITLE
problems in ukf_internal.py and pf_internal.py

### ISSUE THREAD

**Issue by zhchyang2004** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#339]
Hi, there:

Thanks for so professional book! I just found problems from two files discussing with you.

1. In ukf_internal.plot_iscts_two_sensors(), the question is from the triangle calculation.  

    In 'def _isct(pa, pb, alpha, beta)',  b is defined as 'b = pi - beta - ab'. 
    Should it be 'b = pi - beta + ab'?  

2. In pf_internal.py, u is defined as steering and velocity control inputs as indicated in Chapter 12.  
In 'def predict()', you write:
   self.particles[:, 0:2] += u + randn(self.N, 2) * std
   What is the meaning of adding position with u directly? 

   Another question comes from 'def weight'. You write: 
   self.weights += prob
   Should it be 'self.weights *= prob' ? 

Thank you!

**Comment by rlabbe** [comment]
1. I've simplified the math for isct, the question is no longer relevant since I'm using different equations.

2. I don't see the code you state. I write

    self.particles[:, 2] += u[0] + randn(self.N) * std[0]

which is completely different from what you wrote. [:,2] is the column vector of headings.

3. No, I'm adding a small positive value to all values to ensure no probability is zero. Multiplying would still result in zero for some weights. It's not mathematically correct, but an extremely common way of dealing with this situation.
