### ISSUE TITLE
Need explanation on how does the belief in chapter 2's perfect_predict

### ISSUE THREAD

**Issue by geohuz** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#371]
In chapter 2, I saw the ``belief = np.array([.35, .1, .2, .3, 0, 0, 0, 0, 0, .05])`` and then passed into perfect_predict function, but I can't figure out how does the array element assigned the given values?

**Comment by rlabbe** [comment]
I don't know what you mean by " how does the array element assigned the given values?" Do you mean where did .35, .1., etc come from? They are just made up - this is just an example belief distribution; I could use any numbers here as long as they sum to 1 (since the total probability must equal 1).

**Comment by geohuz** [comment]
@rlabbe thanks for the prompt reply! Now that's fair enough.
