### ISSUE TITLE
Heading: Likely a hidden/observable variable

### ISSUE THREAD

**Issue by David-OConnor** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#58]
Chapter five, near the bottom: "the aircraft's state includes things such as as heading, engine RPM, weight, color, the first name of the pilot, and so on. We cannot sense these directly using the position sensor so they are not observed."

It seems to me like the aircraft's heading would be an observable, hidden variable like  velocity; you could estimate it, and use it to improve your results, the same way you did with velocity.

**Comment by rlabbe** [comment]
I admittedly didn't go into details. First, terminology: heading is where you are pointed in space, ground track is the direction of movement. They can be quite biased for an fixed wing aircraft because they have to crab into the wind, and regularly bear no relation in a rotor aircraft (helicopters fly sideways and backwards in low speed flight). 

If you have a crosswind estimate you surely can estimate heading; I did it all the time in my last job. But I am assuming only position is directly observable. But heading is at least *partially observable*, I guess. You could argue giving heading +/- 90 degrees (just say it is the same as the track, you won't be crabbing more than 90 degrees in either direction). But even that assumes normal flight. If the plan is spinning in a stall or engaging in acrobatic maneuvers, the heading could bear no relation to the ground track. In short, you'd never couple the GPS estimated heading to an HSI - it's far too unreliable unaided to make any flight control decisions. 'aiding' typically includes and INS and wind speed pitot. We used to (early 90s) also use VOR and TACAN as that provides an angle relative to the airframe - I have no idea if that is done anymore. 

This is all probably too much detail for the book, and you are right that it is at least partially observable in some circumstances, so I'll need to revise that section. Thanks!

**Comment by David-OConnor** [comment]
Thanks for the detailed explanation! Btw, this book is outstanding; by bar the most accessible explanation of KFs I've come across.
