### ISSUE TITLE
Question: Measurement space in Kalman filter

### ISSUE THREAD

**Issue by Gluttton** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#78]
This is not an issue but a question.

In chapter 6 "Multivariate Kalman Filters" you mention the _measurement_ space. Mostly the reason of using the measurement space is clear, but I have a several questions.

1. First of all I'd like to know how called the opposite of the _measurement_ space? I guess that it might be called the _state_ space, am I right?

2. Some members (Residual, Measurement and Covariance) of equations are explicit belong to the measurement space, but other not. So my question is: which members are belong to the measurement space and which members are not:
 - State (obviously no).
 - Covariance (yes);
 - State transition function (looks like no);
 - Process noise (looks like yes);
 - Control input (looks like no);
 - Control function (looks like no);
 - Residual (yes);
 - Measurement (yes);
 - Measurement function (?);
 - Measurement noise (looks like yes);
 - System uncertainty (looks like yes);
 - Kalman gain (?!).

  Or other words: to respect your example about measurement of temperature, what units (Volt, Celsius, Volt/Celsius, etc) must have each member?

3. This question is consequence of previous question. The most obscure for me how we can update State by adding previous state estimation (which is not in the measurement space) and Residual (which is in the measurement space)? Does Kalman gain performs transformation of Residual?

Thanks!

P.S. Sorry if answers on this questions already are in your book but I have not found their.

**Comment by rlabbe** [comment]
Yes, the opposite of measurement space in this context is the state space.


measurement, measurement noise, system uncertainty, and kalman gain are all
in measurement space. The rest are in space taste, including the
covariance. Think of this in terms of a temperature sensor that reports
volts. Anything that is a volt is in measurement space. Anything that is a
degree is state space. The covariance P would contain the variance in C^2,
and is in state space. The measurement noise matrix would have variance in
V^2, and so is in measurement space.

Kalman gain has an H^T term in it, so that Ky ends up being back in state
space.

**Comment by Gluttton** [comment]
Thanks for your detailed answer!

> measurement, measurement noise, system uncertainty, and kalman gain are all in measurement space. The rest are in space taste, including the covariance.

It looks like you forgot to include Residual to measurement space, am I right?

**Comment by rlabbe** [comment]
Correct, residual is y = z - Hx, which puts it in measurement space.

**Comment by Gluttton** [comment]
Thanks!
