### ISSUE TITLE
Code not compiling in chapter 1

### ISSUE THREAD

**Issue by msadowski** [rlabbe/Kalman-and-Bayesian-Filters-in-Python#82]
Hi there,

In [binder](http://app.mybinder.org/1906349952/notebooks/01-g-h-filter.ipynb) if I try to compile this listing:
```
import book_plots
from book_plots import interactive_plot
import gh_internal as gh
import matplotlib.pyplot as plt


weights = [158.0, 164.2, 160.3, 159.9, 162.1, 164.6, 
           169.6, 167.4, 166.4, 171.0, 171.2, 172.6]

time_step = 1 # day
scale_factor = 4/10

def predict_using_gain_guess(weight, gain_rate, do_print=True, sim_rate=0): 
    # store the filtered results
    estimates, predictions = [weight], []

    # most filter literature uses 'z' for measurements
    for z in weights: 
        # predict new position
        prediction = weight + gain_rate * time_step

        # update filter 
        weight = prediction + scale_factor * (z - prediction)

        # save
        estimates.append(weight)
        predictions.append(prediction)
        if do_print:
            gh.print_results(estimates, prediction, weight)

    # plot results
    gh.plot_gh_results(weights, estimates, predictions, sim_rate)
    
initial_guess = 160.
with interactive_plot():
    predict_using_gain_guess(weight=initial_guess, gain_rate=1)   
```
The following exception is thrown:
```
ImportError                               Traceback (most recent call last)
<ipython-input-1-1dc46de6cfa4> in <module>()
----> 1 import book_plots
      2 from book_plots import interactive_plot
      3 import gh_internal as gh
      4 import matplotlib.pyplot as plt
      5 

ImportError: No module named 'book_plots'
```
If I change the import from <code>import book_plots</code> to <code>import code.book_plots</code> it seems to behave better but then the exception is thrown about filterpy:
```
/home/main/notebooks/book_format.py in test_filterpy_version()
     45 def test_filterpy_version():
     46 
---> 47     import filterpy
     48     from distutils.version import LooseVersion
     49 

ImportError: No module named 'filterpy'
```

**Comment by rlabbe** [comment]
Okay, a couple of things seem to be happening here.

First, is this your personal binder build, or mine? It appears that my last binder build failed to include the requirements.txt file, so filterpy was not included in the build. My fault. But if you did your own build you will need to select requirements.txt when you do the build.

I've made a new build and filterpy is correctly included. Sorry for the mix up. I just executed all the cells in chapter one and received no error messages. Please let me know if it continues to fail for you.

Second problem (maybe). You need to run the cells in order. The topmost cell imports book_format, which does things like set the path for the /code directory, makes sure the correct filterpy is installed, etc. Your PR makes me realize that I really need to notate that this cell must be run first. I'm assuming that the failure to import book_plots was due to the first cell not being executed. Please let me know if this continues to happen with the new binder build I just made.

Also, perhaps I should change my imports to code.xxx? It would make the need to change the path unnecessary, giving people a higher chance of success if they do forget to execute the first cell. I'll have to test that before doing anything about it, though.

**Comment by msadowski** [comment]
The problem I described was in your binder build (the one your repo links to). I just checked your binder build and it seems to work fine now.

I didn't realize I had to run the cells in order, thanks for the information! (It's the first time for me to use jupyter). Somehow I assumed that the first code snippet is run automatically when I open the chapter. 

I don't think you have to change your imports to code.xxx, it might be enough that you point it out somewhere (Or you already did point that out and I missed it, which is quite probable!). 

Another observation: I noticed that in the case of binder python2 kernel throws error in the same snippet I mentioned in the original issue:
```
ImportError                               Traceback (most recent call last)
<ipython-input-4-1dc46de6cfa4> in <module>()
----> 1 import book_plots
      2 from book_plots import interactive_plot
      3 import gh_internal as gh
      4 import matplotlib.pyplot as plt
      5 

ImportError: No module named book_plots
```
I don't know about your plans for supporting Python2, In my case I struggled a lot to set it up  on my PC to work with Python2 but had some problems along the way. I found that setting it up using Python3 modules is much easier and less problematic (probably because I had Python2 and Python3 installed and I might have used the wrong version of pip at some point).

**Comment by rsvp** [comment]
@msadowski Since the modules import absolute_import, try for example: 

`from code import book_plots`

`from code.book_plots import interactive_plot`

This import style should be both python 2.7 and 3* compatible.

**Comment by rlabbe** [comment]
I just pushed a version that I tested completely in Python 2.7. Every notebook runs on my machine. The only real problem I encountered was my use of

    foo_fn(*a, *b)

in a few places, and apparently Python 2.7 does not understand that. That was only in Chapter 3. If you have other issues, it would be great to hear the details.
